<?php if ( $sorry ) { ?>
	<p class="sorry">404 no such file</p>
<?php } else {?>
  <div id="focus">
  	<h1><?=htmlspecialchars($file['name'])?></h1>
  	
  	<div id="upload-instructions">
  	  <div align="center" id="browser-header">Download from command line:</div>
	    <code><?=($file['password_protected'] ? "curl -H 'Authorization: yourpassword' " : 'wget ')?><?=htmlspecialchars(upload_base_url() . '/' . $file['id'] . '/' . rawurlencode($file['name']))?></code>
  	</div>
  	
  	<p class="note" align="center">
		  <a href="<?=htmlspecialchars('/' . $file['id'] . '/' . rawurlencode($file['name']))?>?download=1">Direct download</a>
  		(<?=number_format($file['size'] / 1024, 1, '.', ',')?> KB)
  	</p>
  	
  	<input type="text" id="copy"/>
	</div>
<?php } ?>
