<?php

# Output streamed if was fed

if ( $error )
{
	echo "\n";
	echo 'Error: ';
	echo $error . "\n\n";
}

if ( $uploads )
{
	echo "\n";
	
	echo '=========================';
	
	echo "\n\n";

	$total = 0;
	foreach ( $uploads as $file ) $total += $file['size'];

	echo 'Uploaded ' .
			count($uploads) . ' file, ' .
			number_format($total, 0, '.', ' ') . ' bytes' . "\n\n";

	foreach ( $uploads as $file ) 
	{
		$url = file_url($file);
		if ( $file['password_protected'] ) {
			echo "curl -H 'Authorization: yourpassword' {$url} -o " . $file['name'] . "\n";
		}
		else {
			echo "wget {$url}" . "\n";
		}
    echo "\n";
	}
	
	echo '=========================';
	echo "\n\n";
}
